import fs from 'fs'
import path from 'path'

const postsDir = './content/posts'
const outputFile = './src/posts-data.ts'

const VALID_LOCALES = ['en', 'uk']
const VALID_CATEGORIES = ['iot', 'saltstack', 'kubernetes', 'blog']

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/)
  if (!match) return { meta: {}, body: content }

  const meta = {}
  match[1].split('\n').forEach(line => {
    const colonIdx = line.indexOf(':')
    if (colonIdx === -1) return
    const key = line.slice(0, colonIdx).trim()
    const value = line.slice(colonIdx + 1).trim()
    meta[key] = value
  })

  return { meta, body: match[2].trim() }
}

const posts = []

for (const locale of VALID_LOCALES) {
  for (const category of VALID_CATEGORIES) {
    const dir = path.join(postsDir, locale, category)
    if (!fs.existsSync(dir)) continue

    const files = fs.readdirSync(dir).filter(f => f.endsWith('.md')).sort()

    for (const file of files) {
      const slug = file.replace(/\.md$/, '')
      const raw = fs.readFileSync(path.join(dir, file), 'utf-8')
      const { meta, body } = parseFrontmatter(raw)

      posts.push({
        slug,
        locale,
        category,
        title: meta.title ?? slug,
        date: meta.date ?? '',
        description: meta.description ?? '',
        tags: meta.tags ? meta.tags.split(',').map(t => t.trim()) : [],
        content: body,
      })
    }
  }
}

posts.sort((a, b) => (a.date < b.date ? 1 : -1))

const output = `// Auto-generated by scripts/build-posts.mjs — do not edit manually
export interface Post {
  slug: string
  locale: string
  category: string
  title: string
  date: string
  description: string
  tags: string[]
  content: string
}

export const posts: Post[] = ${JSON.stringify(posts, null, 2)}
`

fs.writeFileSync(outputFile, output)

const byLocale = Object.fromEntries(VALID_LOCALES.map(l => [l, posts.filter(p => p.locale === l).length]))
const summary = VALID_LOCALES.map(l => `${l}: ${byLocale[l]}`).join(', ')
console.log(`Built ${posts.length} post(s) [${summary}] → ${outputFile}`)
